 apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: kube-web-view
   namespace: tools
   annotations:
     nginx.ingress.kubernetes.io/whitelist-source-range: IP_ADDRESS/32
 spec:
   ingressingressClassName: nginx
   rules:
   - host: kube-view.domain.xyz
     http:
       paths:
       - path: /
         backend:
           service:
            name: kube-web-view
            port: 
              number: 80
         pathType: Prefix